/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoparcial;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author alexi
 */
public class Ejercicio24 extends javax.swing.JPanel {

    /**
     * Creates new form Ejercicio24
     */
    public Ejercicio24() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabla2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));

        Tabla1.setBackground(new java.awt.Color(204, 255, 255));
        Tabla1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Nombre", "Peso", "Altura", "IMC", "Diagnostico"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Tabla1);

        jButton1.setBackground(new java.awt.Color(255, 204, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 204, 204));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Añadir ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        Tabla2.setBackground(new java.awt.Color(204, 204, 255));
        Tabla2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Tabla2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Bajo de peso", "0", "0"},
                {"Normal", "0", "0"},
                {"SobrePeso", "0", "0"},
                {"Obesidad", "0", "0"},
                {"Total", "0", "0"}
            },
            new String [] {
                "IMC", "Cantidad", "%"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(Tabla2);

        jLabel1.setBackground(new java.awt.Color(204, 255, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("24. Ingresar de un conjunto de N pacientes los siguientes datos: estatura (en metros) y peso (Kg). Calcular por cada paciente el índice de masa muscular (IMC)");
        jLabel1.setOpaque(true);

        jButton3.setBackground(new java.awt.Color(255, 204, 204));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("Nuevo");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel2.setText("Hecho por Alexis Pesantez");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DefaultTableModel modelo = (DefaultTableModel)Tabla1.getModel();
        try{
            int N = modelo.getRowCount();
            modelo.setRowCount(++N);
            for (int i=1;i<=N;i++)
            modelo.setValueAt("" + i, i-1, 0);
        }
        catch (Exception ex){}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            DefaultTableModel modelo = (DefaultTableModel) Tabla1.getModel();
            int N = modelo.getRowCount();
            int bajoPeso = 0, normal = 0, sobrePeso = 0, obesidad = 0;

            for (int fila = 0; fila < N; fila++) {
                double altura = Double.parseDouble(Tabla1.getValueAt(fila, 3).toString());
                double peso = Double.parseDouble(Tabla1.getValueAt(fila, 2).toString());
                double imc = peso / Math.pow(altura, 2);

                if (imc < 18.5) {
                    bajoPeso++;
                    modelo.setValueAt("Peso Bajo", fila, 5);
                } else if (imc >= 18.5 && imc < 25) {
                    normal++;
                    modelo.setValueAt("Peso normal", fila, 5);
                } else if (imc >= 25 && imc < 30) {
                    sobrePeso++;
                    modelo.setValueAt("Sobre Peso", fila, 5);
                } else {
                    obesidad++;
                    modelo.setValueAt("Obesidad", fila, 5);
                }

                // GRUPO #3
                modelo.setValueAt(String.format("%.2f", imc), fila, 4);
            }

            Tabla2.setValueAt("" + bajoPeso, 0, 1);
            double pbajo = ((double) bajoPeso / N) * 100;
            Tabla2.setValueAt(String.format("%.2f%%", pbajo), 0, 2);

            Tabla2.setValueAt("" + normal, 1, 1);
            double pnormal = ((double) normal / N) * 100;
            Tabla2.setValueAt(String.format("%.2f%%", pnormal), 1, 2);

            Tabla2.setValueAt("" + sobrePeso, 2, 1);
            double psobre = ((double) sobrePeso / N) * 100;
            Tabla2.setValueAt(String.format("%.2f%%", psobre), 2, 2);

            Tabla2.setValueAt("" + obesidad, 3, 1);
            double pobesidad = ((double) obesidad / N) * 100;
            Tabla2.setValueAt(String.format("%.2f%%", pobesidad), 3, 2);

            int total = bajoPeso + normal + sobrePeso + obesidad;
            Tabla2.setValueAt("" + total, 4, 1);
            Tabla2.setValueAt("100.00%", 4, 2);

        } catch (Exception ex) {
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
       Tabla2.setValueAt(0,0, 1);
       Tabla2.setValueAt(0,0, 2);
       Tabla2.setValueAt(0,1, 1);
       Tabla2.setValueAt(0,1, 2);
       Tabla2.setValueAt(0,2, 1);
       Tabla2.setValueAt(0,2, 2);
       Tabla2.setValueAt(0,3, 1);
       Tabla2.setValueAt(0,3, 2);
       Tabla2.setValueAt(0,4, 1);
       Tabla2.setValueAt(0,4, 2);
       
       }
       catch(Exception ex){   
       }
       DefaultTableModel model = (DefaultTableModel) Tabla1.getModel();
       model.setRowCount(0);
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla1;
    private javax.swing.JTable Tabla2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
