
package proyectoparcial;

import javax.swing.JOptionPane;
public class Ejercicio1 extends javax.swing.JPanel {

    /**
     * Creates new form Ejercicio1
     */
    public Ejercicio1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CALCULAR = new javax.swing.JButton();
        titulardo = new javax.swing.JLabel();
        NUEVO = new javax.swing.JButton();
        ekisde = new javax.swing.JLabel();
        xd = new javax.swing.JLabel();
        finalpe = new javax.swing.JTextField();
        inicio = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tx1 = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(204, 204, 204));

        CALCULAR.setBackground(new java.awt.Color(255, 255, 204));
        CALCULAR.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        CALCULAR.setText("CALCULAR");
        CALCULAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CALCULARActionPerformed(evt);
            }
        });

        titulardo.setBackground(new java.awt.Color(204, 255, 204));
        titulardo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        titulardo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulardo.setText("1. Generar la serie de números múltiplos de M, hasta un límite N que debe ingresar el usuario.");
        titulardo.setOpaque(true);

        NUEVO.setBackground(new java.awt.Color(255, 255, 204));
        NUEVO.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        NUEVO.setText("NUEVO");
        NUEVO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NUEVOActionPerformed(evt);
            }
        });

        ekisde.setBackground(new java.awt.Color(255, 255, 204));
        ekisde.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ekisde.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ekisde.setText("Poner número N");
        ekisde.setOpaque(true);

        xd.setBackground(new java.awt.Color(255, 255, 204));
        xd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        xd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        xd.setText("Poner número M");
        xd.setOpaque(true);
        xd.setPreferredSize(new java.awt.Dimension(129, 22));

        finalpe.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        finalpe.setPreferredSize(new java.awt.Dimension(129, 22));

        inicio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        inicio.setPreferredSize(new java.awt.Dimension(129, 22));
        inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicioActionPerformed(evt);
            }
        });

        tx1.setColumns(20);
        tx1.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        tx1.setRows(5);
        jScrollPane1.setViewportView(tx1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titulardo, javax.swing.GroupLayout.DEFAULT_SIZE, 1066, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(xd, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ekisde, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(inicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(finalpe, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CALCULAR, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NUEVO, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titulardo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CALCULAR, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ekisde, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(xd, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(finalpe, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NUEVO, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(136, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CALCULARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CALCULARActionPerformed
        int m=0, n=0, s;
            try {
            m = Integer.parseInt(inicio.getText());
            n = Integer.parseInt(finalpe.getText());
            }
            catch (Exception ex){
                JOptionPane.showMessageDialog(this, "Ingrese valores numericos con N y M");
                return;
            }
        s=m;
        tx1.setText("HECHO POR:ALEXIS PESANTEZ \n");
        while (s<=n){ 
            tx1.append(s + " ");
            s +=m;
        }
    }//GEN-LAST:event_CALCULARActionPerformed

    private void NUEVOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NUEVOActionPerformed
        inicio.setText("");
        finalpe.setText("");
        tx1.setText("Ingrese valores numericos con N y M");
        
    }//GEN-LAST:event_NUEVOActionPerformed

    private void inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inicioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CALCULAR;
    private javax.swing.JButton NUEVO;
    private javax.swing.JLabel ekisde;
    private javax.swing.JTextField finalpe;
    private javax.swing.JTextField inicio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel titulardo;
    private javax.swing.JTextArea tx1;
    private javax.swing.JLabel xd;
    // End of variables declaration//GEN-END:variables
}
