/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoparcial;

import java.awt.CardLayout;
public class FormularioGeneral extends javax.swing.JFrame {

    /**
     * Creates new form FormularioGeneral
     */
    public FormularioGeneral() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txTitulo = new javax.swing.JLabel();
        txPie = new javax.swing.JLabel();
        PanelMenu = new javax.swing.JPanel();
        botonejer1 = new javax.swing.JButton();
        casa = new javax.swing.JButton();
        botonejer7 = new javax.swing.JButton();
        bottton9 = new javax.swing.JButton();
        bottton10 = new javax.swing.JButton();
        bottton11 = new javax.swing.JButton();
        bottton12 = new javax.swing.JButton();
        bottton13 = new javax.swing.JButton();
        bottton14 = new javax.swing.JButton();
        bottton15 = new javax.swing.JButton();
        bottton16 = new javax.swing.JButton();
        PanelCentral = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txTitulo.setBackground(new java.awt.Color(102, 153, 255));
        txTitulo.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        txTitulo.setForeground(new java.awt.Color(255, 255, 255));
        txTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txTitulo.setText("Proyecto Parcial 1 - Fundamentos de programación");
        txTitulo.setOpaque(true);
        txTitulo.setPreferredSize(new java.awt.Dimension(293, 55));
        getContentPane().add(txTitulo, java.awt.BorderLayout.PAGE_START);

        txPie.setBackground(new java.awt.Color(102, 204, 255));
        txPie.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txPie.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txPie.setText("®UTMACH - Alexis Andree Pesantez Cordova    ");
        txPie.setOpaque(true);
        txPie.setPreferredSize(new java.awt.Dimension(275, 35));
        getContentPane().add(txPie, java.awt.BorderLayout.PAGE_END);

        PanelMenu.setBackground(new java.awt.Color(153, 153, 153));
        PanelMenu.setPreferredSize(new java.awt.Dimension(220, 773));

        botonejer1.setBackground(new java.awt.Color(0, 0, 0));
        botonejer1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonejer1.setForeground(new java.awt.Color(255, 255, 255));
        botonejer1.setText("Ejercicio 1");
        botonejer1.setContentAreaFilled(false);
        botonejer1.setOpaque(true);
        botonejer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonejer1ActionPerformed(evt);
            }
        });

        casa.setBackground(new java.awt.Color(153, 153, 153));
        casa.setForeground(new java.awt.Color(153, 153, 153));
        casa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoparcial/Recursos/casdasdas.png"))); // NOI18N
        casa.setBorderPainted(false);
        casa.setContentAreaFilled(false);
        casa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casaActionPerformed(evt);
            }
        });

        botonejer7.setBackground(new java.awt.Color(0, 0, 0));
        botonejer7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonejer7.setForeground(new java.awt.Color(255, 255, 255));
        botonejer7.setText("Ejercicio 7");
        botonejer7.setContentAreaFilled(false);
        botonejer7.setOpaque(true);
        botonejer7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonejer7ActionPerformed(evt);
            }
        });

        bottton9.setBackground(new java.awt.Color(0, 0, 0));
        bottton9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bottton9.setForeground(new java.awt.Color(255, 255, 255));
        bottton9.setText("Ejercicio 9");
        bottton9.setContentAreaFilled(false);
        bottton9.setOpaque(true);
        bottton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottton9ActionPerformed(evt);
            }
        });

        bottton10.setBackground(new java.awt.Color(0, 0, 0));
        bottton10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bottton10.setForeground(new java.awt.Color(255, 255, 255));
        bottton10.setText("Ejercicio 14");
        bottton10.setContentAreaFilled(false);
        bottton10.setOpaque(true);
        bottton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottton10ActionPerformed(evt);
            }
        });

        bottton11.setBackground(new java.awt.Color(0, 0, 0));
        bottton11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bottton11.setForeground(new java.awt.Color(255, 255, 255));
        bottton11.setText("Ejercicio 20");
        bottton11.setContentAreaFilled(false);
        bottton11.setOpaque(true);
        bottton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottton11ActionPerformed(evt);
            }
        });

        bottton12.setBackground(new java.awt.Color(0, 0, 0));
        bottton12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bottton12.setForeground(new java.awt.Color(255, 255, 255));
        bottton12.setText("Ejercicio 24");
        bottton12.setContentAreaFilled(false);
        bottton12.setOpaque(true);
        bottton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottton12ActionPerformed(evt);
            }
        });

        bottton13.setBackground(new java.awt.Color(0, 0, 0));
        bottton13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bottton13.setForeground(new java.awt.Color(255, 255, 255));
        bottton13.setText("Ejercicio 25");
        bottton13.setContentAreaFilled(false);
        bottton13.setOpaque(true);
        bottton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottton13ActionPerformed(evt);
            }
        });

        bottton14.setBackground(new java.awt.Color(0, 0, 0));
        bottton14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bottton14.setForeground(new java.awt.Color(255, 255, 255));
        bottton14.setText("Ejercicio 29");
        bottton14.setContentAreaFilled(false);
        bottton14.setOpaque(true);
        bottton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottton14ActionPerformed(evt);
            }
        });

        bottton15.setBackground(new java.awt.Color(0, 0, 0));
        bottton15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bottton15.setForeground(new java.awt.Color(255, 255, 255));
        bottton15.setText("Ejercicio 33");
        bottton15.setContentAreaFilled(false);
        bottton15.setOpaque(true);
        bottton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottton15ActionPerformed(evt);
            }
        });

        bottton16.setBackground(new java.awt.Color(0, 0, 0));
        bottton16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bottton16.setForeground(new java.awt.Color(255, 255, 255));
        bottton16.setText("Ejercicio 38");
        bottton16.setContentAreaFilled(false);
        bottton16.setOpaque(true);
        bottton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottton16ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelMenuLayout = new javax.swing.GroupLayout(PanelMenu);
        PanelMenu.setLayout(PanelMenuLayout);
        PanelMenuLayout.setHorizontalGroup(
            PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMenuLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bottton16, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bottton15, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bottton14, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bottton13, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bottton12, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bottton11, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bottton10, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonejer7, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonejer1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bottton9, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelMenuLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(casa, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        PanelMenuLayout.setVerticalGroup(
            PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(casa)
                .addGap(37, 37, 37)
                .addComponent(botonejer1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonejer7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bottton9, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bottton10, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bottton11, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bottton12, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bottton13, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bottton14, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bottton15, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bottton16, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        getContentPane().add(PanelMenu, java.awt.BorderLayout.LINE_START);

        PanelCentral.setBackground(new java.awt.Color(255, 255, 255));
        PanelCentral.setLayout(new java.awt.CardLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoparcial/Recursos/CAPTURA.png"))); // NOI18N
        PanelCentral.add(jLabel1, "card2");

        getContentPane().add(PanelCentral, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void casaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casaActionPerformed
        PanelCentral.add(new INICIO_CASA(), "CASA");
        try{
            CardLayout c1 = (CardLayout)(PanelCentral.getLayout());
            c1.show(PanelCentral, "CASA");
        }catch (Exception ex){}
        PanelCentral.repaint();
    }//GEN-LAST:event_casaActionPerformed

    private void botonejer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonejer1ActionPerformed
       PanelCentral.add(new Ejercicio1(), "Ejercicio1");
        try{
            CardLayout c1 = (CardLayout)(PanelCentral.getLayout());
            c1.show(PanelCentral, "Ejercicio1");
        }catch (Exception ex){}
        PanelCentral.repaint();

    }//GEN-LAST:event_botonejer1ActionPerformed

    private void botonejer7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonejer7ActionPerformed
        PanelCentral.add(new Ejercicio7(), "Ejercicio7");
        try{
            CardLayout c1 = (CardLayout)(PanelCentral.getLayout());
            c1.show(PanelCentral, "Ejercicio7");
        }catch (Exception ex){}
        PanelCentral.repaint();
        
    }//GEN-LAST:event_botonejer7ActionPerformed

    private void bottton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottton9ActionPerformed
        PanelCentral.add(new Ejercicio9(), "Ejercicio9");
        try{
            CardLayout c1 = (CardLayout)(PanelCentral.getLayout());
            c1.show(PanelCentral, "Ejercicio9");
        }catch (Exception ex){}
        PanelCentral.repaint();
        
    }//GEN-LAST:event_bottton9ActionPerformed

    private void bottton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottton10ActionPerformed
       PanelCentral.add(new Ejercicio14(), "Ejercicio14");
        try{
            CardLayout c1 = (CardLayout)(PanelCentral.getLayout());
            c1.show(PanelCentral, "Ejercicio14");
        }catch (Exception ex){}
        PanelCentral.repaint();
    }//GEN-LAST:event_bottton10ActionPerformed

    private void bottton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottton11ActionPerformed
        PanelCentral.add(new Ejercicio20(), "Ejercicio20");
        try{
            CardLayout c1 = (CardLayout)(PanelCentral.getLayout());
            c1.show(PanelCentral, "Ejercicio20");
        }catch (Exception ex){}
        PanelCentral.repaint();
    }//GEN-LAST:event_bottton11ActionPerformed

    private void bottton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottton12ActionPerformed
        PanelCentral.add(new Ejercicio24(), "Ejercicio24");
        try{
            CardLayout c1 = (CardLayout)(PanelCentral.getLayout());
            c1.show(PanelCentral, "Ejercicio24");
        }catch (Exception ex){}
        PanelCentral.repaint();
    }//GEN-LAST:event_bottton12ActionPerformed

    private void bottton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottton13ActionPerformed
        PanelCentral.add(new Ejercicio25(), "Ejercicio25");
        try{
            CardLayout c1 = (CardLayout)(PanelCentral.getLayout());
            c1.show(PanelCentral, "Ejercicio25");
        }catch (Exception ex){}
        PanelCentral.repaint();
    }//GEN-LAST:event_bottton13ActionPerformed

    private void bottton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottton14ActionPerformed
       PanelCentral.add(new Ejercicio29(), "Ejercicio29");
        try{
            CardLayout c1 = (CardLayout)(PanelCentral.getLayout());
            c1.show(PanelCentral, "Ejercicio29");
        }catch (Exception ex){}
        PanelCentral.repaint();
    }//GEN-LAST:event_bottton14ActionPerformed

    private void bottton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottton15ActionPerformed
        PanelCentral.add(new Ejercicio33(), "Ejercicio33");
        try{
            CardLayout c1 = (CardLayout)(PanelCentral.getLayout());
            c1.show(PanelCentral, "Ejercicio33");
        }catch (Exception ex){}
        PanelCentral.repaint();
    }//GEN-LAST:event_bottton15ActionPerformed

    private void bottton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottton16ActionPerformed
       PanelCentral.add(new Ejercicio38(), "Ejercicio38");
        try{
            CardLayout c1 = (CardLayout)(PanelCentral.getLayout());
            c1.show(PanelCentral, "Ejercicio38");
        }catch (Exception ex){}
        PanelCentral.repaint();
    }//GEN-LAST:event_bottton16ActionPerformed

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioGeneral().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelCentral;
    private javax.swing.JPanel PanelMenu;
    private javax.swing.JButton botonejer1;
    private javax.swing.JButton botonejer7;
    private javax.swing.JButton bottton10;
    private javax.swing.JButton bottton11;
    private javax.swing.JButton bottton12;
    private javax.swing.JButton bottton13;
    private javax.swing.JButton bottton14;
    private javax.swing.JButton bottton15;
    private javax.swing.JButton bottton16;
    private javax.swing.JButton bottton9;
    private javax.swing.JButton casa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel txPie;
    private javax.swing.JLabel txTitulo;
    // End of variables declaration//GEN-END:variables
}
