/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoparcial;

/**
 *
 * @author alexi
 */
public class INICIO_CASA extends javax.swing.JPanel {

    /**
     * Creates new form INICIO_CASA
     */
    public INICIO_CASA() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ICON = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.CardLayout());

        ICON.setBackground(new java.awt.Color(255, 255, 255));
        ICON.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ICON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoparcial/Recursos/CAPTURA.png"))); // NOI18N
        add(ICON, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ICON;
    // End of variables declaration//GEN-END:variables
}
